---

- hosts: localhost
  connection: local
  any_errors_fatal: True
  become: True
  roles:
    - role: roles/action/setup
    - role: roles/resource/common
    - role: roles/resource/consul
    - role: roles/client
